name: Deploy - Vercel

on:
  workflow_call:
    inputs:
      vercel_token:
        required: true
        description: 'Vercel token for deployment'
      vercel_org_id:
        required: true
        description: 'Vercel organization ID'
      vercel_project_id:
        required: true
        description: 'Vercel project ID'

jobs:
  deploy-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: ./.github/actions/setup-project

      - name: Lint code
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Build app
        run: npm run build

      - name: Deploy app to Vercel
        uses: vercel/action@latest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
