jobs:
  deploy-vercel:
    uses: ./.github/actions/deploy-vercel
    with:
      vercel_token: ${{ secrets.PET_TOKEN }}
      vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
      vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
